## Write a Numpy program to compute the multiplication of two given matrixes

In [6]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print(p)
print(q)
result1 = np.dot(p, q)
print(result1)


[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


## Write a NumPy program to compute the determinant of a given square array

In [8]:
import numpy as np
p = [[1,5], [0, 6]]
print(p)
np.linalg.det(p)


[[1, 5], [0, 6]]


6.0

## Write a NumPy program to compute the cross product of two given vectors

In [10]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print(p)
print(q)
print(np.cross(p,q))
np.cross(q,p)

[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
[ 2 -3]


array([-2,  3])

## Write a NumPy program to compute the condition number of a given matrix

In [12]:
import numpy as np
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print("Original matrix:")
print(a)
print("The condition number of the said matrix:")
print(np.linalg.cond(a))

Original matrix:
[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]
The condition number of the said matrix:
1.4142135623730951


## Write a NumPy program to compute the inverse of a given matrix

In [13]:
p = [[1, 0], [0, 1]]
np.linalg.inv(p)

array([[1., 0.],
       [0., 1.]])